#!/bin/bash 

#add new words entry
path="/Users/`whoami`/Library/Application Support/OpenVanilla/UserData/OVIMGeneric"
dict="$path/"zhengma.cin
new_dict="$dict".bkup
grep -v "%chardef end" "$dict" >"$new_dict"
echo "$1" >> "$new_dict"
echo "%chardef end" >>  "$new_dict"
mv "$new_dict" "$dict"
